module.exports = {
  preset: 'react-native',
  transform: {
    '^.+\\.tsx?$': ['babel-jest', { configFile: './babel.config.test.js' }],
    '^.+\\.jsx?$': ['babel-jest', { configFile: './babel.config.test.js' }],
  },
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|@react-native|react-native-.*|@react-native-community|@react-navigation|@react-native-async-storage|@expo|expo-.*|expo|firebase|@firebase|i18n-js|react-native-paper|react-native-vector-icons|react-native-gesture-handler|react-native-reanimated|react-native-safe-area-context|react-native-screens|react-native-chart-kit|react-native-svg|react-native-web)/)',
  ],
  setupFiles: ['./jest.setup.js'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^react-native-vector-icons/(.*)$': '<rootDir>/__mocks__/react-native-vector-icons.js',
    '^react-native-chart-kit$': '<rootDir>/__mocks__/react-native-chart-kit.js',
    '^expo-router$': '<rootDir>/__mocks__/expo-router.js',
    '^expo-localization$': '<rootDir>/__mocks__/expo-localization.js',
    '^expo-constants$': '<rootDir>/__mocks__/expo-constants.js',
    '^expo-notifications$': '<rootDir>/__mocks__/expo-notifications.js',
    '^expo-device$': '<rootDir>/__mocks__/expo-device.js',
    '^expo-status-bar$': '<rootDir>/__mocks__/expo-status-bar.js',
    '^expo-font$': '<rootDir>/__mocks__/expo-font.js',
    '^expo-linking$': '<rootDir>/__mocks__/expo-linking.js',
    '^expo-haptics$': '<rootDir>/__mocks__/expo-haptics.js',
    '^expo-system-ui$': '<rootDir>/__mocks__/expo-system-ui.js',
    '^expo-web-browser$': '<rootDir>/__mocks__/expo-web-browser.js',
    '^expo-splash-screen$': '<rootDir>/__mocks__/expo-splash-screen.js',
    '^expo-image$': '<rootDir>/__mocks__/expo-image.js',
    '^expo-symbols$': '<rootDir>/__mocks__/expo-symbols.js',
    '^@expo/vector-icons$': '<rootDir>/__mocks__/react-native-vector-icons.js',
    '\\.(png|jpg|jpeg|gif|svg)$': '<rootDir>/__mocks__/fileMock.js',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  testMatch: ['**/__tests__/**/*.test.(ts|tsx|js)'],
  testEnvironment: 'node',
  haste: {
    defaultPlatform: 'android',
    platforms: ['android', 'ios', 'native'],
  },
};
